### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by sofiiadidovych** [HackYourFuture-CPH/node.js#51]
in the 'Getting data through the request body using POST' section there should be a screenshot with some setup, but the page is not found:
https://github.com/HackYourFuture-CPH/node.js/blob/master/assets/calculator-post.PNG

**Comment by nkuik** [comment]
Hi @sofiiadidovych. Thanks for creating this issue.

I was wondering if you had any interest in making a fix for this. The image the link thought it's referring to is located [here](https://github.com/HackYourFuture-CPH/node.js/blob/master/week3/assets/calculator-post.PNG). To make a fix, you could:

1. Move the `calculator-post.PNG` file to the `assets` directory in the repo base (the directory can be found [here](https://github.com/HackYourFuture-CPH/node.js/tree/master/assets)).
2. Change the reference in the [week 3 homework readme](https://github.com/HackYourFuture-CPH/node.js/blob/master/week3/homework-template/readme.md) to make a relative reference to the `calculator-post.PNG` that moved in step 1. You can read about relative references in GitHub repos [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files).

Let me know what you think.

**Comment by sofiiadidovych** [comment]
Hi @nkuik! I will do it with pleasure, but I have a question: do I need to make this change locally and then make a pull request, and then it will be merged to master?

**Comment by nkuik** [comment]
Great! Since you don't have write access to this repo (which is intentional), you will need to make a PR across forks. This means you will need to fork this repo, make the change, and then open a PR back to this repo.

You can read about forking repos [here](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo), and about making a PR across repos [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

Just let me know if you have any questions. Thanks for the help!

**Comment by sofiiadidovych** [comment]
@nkuik everything is done, my PR is here https://github.com/HackYourFuture-CPH/node.js/pull/52
Hope everything works ok)
